# -*- coding: utf-8 -*-
"""AtliqMedia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wblXpdYY1LzVWvO01LscfQ1wJVWWE-Yq

# Tamil Nadu Election Analysis (2021 vs 2026)
## AtliQ Media Resume Project Challenge

---

### Project Objective
This project analyzes how Tamil Nadu's political landscape changed between the 2021 and 2026 Assembly elections using constituency-level and regional-level election data.

### Key Areas of Analysis
- Regional Political Fragmentation
- Constituency-Level Volatility
- Vote Share Dynamics
- TVK's Statewide Emergence

### Tools & Technologies
- Python
- Pandas
- Plotly
- Power BI

---

# Notebook Structure

1. Data Loading & Understanding  
2. Data Cleaning & Validation  
3. Election Winner Analysis  
4. Regional Political Landscape  
5. Constituency Flip Analysis  
6. Vote Share Dynamics  
7. Key Insights & Conclusions  

---

**Domain**:

**Media**/ **Broadcasting**

## Problem Statement

**AtliQ Media** is producing a one-hour TV show on the 2026 Tamil Nadu Assembly election results. Unlike most channels covering the election with debates and political commentary, AtliQ wants the opposite - a clean, fact-based show grounded only in ECI data.


You have been hired as a data analyst to find the most interesting stories in the 2026 results, support each with a clear chart, and pitch them in a way that helps AtliQ plan the show. You are not asked to explain why any party won or lost, or to predict what will happen next.



In 2026, AI can do most of the analysis for you. The real skill being tested is storytelling: picking the right numbers, framing them so a regular viewer understands, and holding their attention without using complicated charts.
"""

# import pandas

import pandas as pd

# import the three dataset provided in the challenge

constituency = pd.read_csv("/content/drive/MyDrive/Atliq Media/constituency_master.csv")

tn_2021_results = pd.read_csv("/content/drive/MyDrive/Atliq Media/tn_2021_results.csv")

tn_2026_results = pd.read_csv("/content/drive/MyDrive/Atliq Media/tn_2026_results.csv")

# Look at some data using head() dataframe
print("Constituency:\n", constituency.head(), "\n\n")

print("tn_2021_results:\n", tn_2021_results.head(), "\n\n")

print("tn_2026_results:\n", tn_2026_results.head())

"""### Data Dictionary

Column Description for tn_2021_results.csv and tn_2026_results.csv:
1. constituency: The name of the Assembly Constituency in Tamil Nadu.
2. ac_number: The official Election Commission AC number (1 to 234). Use this as the primary key when joining files.
3. candidate: The name of the candidate as recorded by the ECI.
4. party: Standardized party abbreviation (DMK, AIADMK, TVK, INC, BJP, PMK, VCK, NTK, CPI, CPI(M), IND, NOTA, etc.).
5. votes: Total votes received by the candidate in that constituency.
6. turnout: Constituency-level voter turnout percentage. This is the same value for every row in a given constituency.
7. reserved: Constituency reservation status. GEN = general / unreserved, SC = reserved for Scheduled Caste, ST = reserved for Scheduled Tribe.
                Tamil Nadu has 188 GEN, 44 SC, and 2 ST constituencies (same in both 2021 and 2026 — no delimitation change).
8. region: Editorial six-region grouping (Chennai Metro, North, Central, Kongu, Delta, South). This is NOT an official ECI classification — it is the grouping convention used in this challenge to enable regional analysis. See constituency_master.csv for the full mapping.



Column Description for constituency_master.csv:
1. ac_number: Official ECI AC number (1 to 234).
2. constituency: AC name.
3. district: Administrative district the constituency belongs to.
4. region: Six-region editorial grouping (Chennai Metro, North, Central, Kongu, Delta, South).
5. reserved: GEN, SC, or ST.

"""

# Let's look at tables using dataframes.
# Let's know the the number of rows and columns in each tables.

print("Constituency:\n", constituency.shape, "\n\n")
print("tn_2021_results:\n", tn_2021_results.shape, "\n\n")
print("tn_2026_results):\n", tn_2026_results.shape)

# Let's know the column name of each tables.

print("Constituency\n",constituency.columns,"\n")
print("tn_2021_results\n",tn_2021_results.columns,"\n")
print("tn_2026_results\n",tn_2026_results.columns,"\n")

# Let's know the information of each tables.

print("Constituency:\n")
print(constituency.info(),"\n")
print("tn_2021_results:\n")
print(tn_2021_results.info(),"\n")
print("tn_2026_results:\n")
print(tn_2026_results.info())

# Check for duplicates

print("Constituency:\n", constituency.duplicated().sum(), "\n")
print("tn_2021_results:\n", tn_2021_results.duplicated().sum(), "\n")
print("tn_2026_results:\n", tn_2026_results.duplicated().sum())

# Check for missing values

# Constituency
print("Constituency\n")
print(constituency.isnull().sum(),"\n")

# tn_2021_results
print("tn_2021_results\n")
print(tn_2021_results.isnull().sum(),"\n")

# tn_2026_result
print("tn_2026_results\n")
print(tn_2026_results.isnull().sum())

# Unique rows
tn_2021_results['ac_number'].nunique()

# Unique rows
tn_2026_results['ac_number'].nunique()

# Unique rows
constituency['ac_number'].nunique()

# Find index of candidate with maximum votes in each constituency

winner_index_2021 = tn_2021_results.groupby('ac_number')['votes'].idxmax()

# Create winners table

winners_2021 = tn_2021_results.loc[winner_index_2021]

# Display result

winners_2021.head()

# Unique rows
winner_index_2021.index.nunique()

winner_index_2021.head()

winners_2021.shape

# Find index of candidate with maximum votes in each constituency

winner_index_2026 = tn_2026_results.groupby('ac_number')['votes'].idxmax()

# Create winners table

winners_2026 = tn_2026_results.loc[winner_index_2026]

# Display result

winners_2026.head()

# Rename columns
# This avoids confusion after merging.
winners_2021 = winners_2021.rename(columns={
    'candidate': 'winner_candidate_2021',
    'party': 'winner_party_2021',
    'votes': 'winner_votes_2021',
    'turnout': 'turnout_2021'
})

winners_2026 = winners_2026.rename(columns={
    'candidate': 'winner_candidate_2026',
    'party': 'winner_party_2026',
    'votes': 'winner_votes_2026',
    'turnout': 'turnout_2026'
})

winners_2021

winners_2026

# Merge both election years

# This is one of the MOST important tables in the project.

"""
Merge 2021 and 2026 winners tables using constituency (ac_number)
to create a constituency-level election comparison dataset.
This table will be used for flip analysis, regional shifts,
seat comparison, and other cross-year election insights.
"""

election_comparison = pd.merge(
    winners_2021,
    winners_2026,
    on='ac_number',
    suffixes=('_2021', '_2026')
)

election_comparison.head()

# create flip column
election_comparison['flipped'] = (
    election_comparison['winner_party_2021']
    != election_comparison['winner_party_2026']
)

"""A **flip** happens when the party that won a constituency in the previous election no longer wins it in the next election."""

# Check number of flipped constituencies
election_comparison['flipped'].value_counts()

"""
Group the 2021 winners data by region and winning party
to calculate the number of seats won by each party
in each region during the 2021 Tamil Nadu Assembly election.
"""

region_2021 = (
    winners_2021
    .groupby(['region', 'winner_party_2021'])
    .size()
    .reset_index(name='seats_2021')
)

region_2021.head()

"""
Group the 2026 winners data by region and winning party
to calculate the number of seats won by each party
in each region during the 2021 Tamil Nadu Assembly election.
"""

region_2026 = (
    winners_2026
    .groupby(['region', 'winner_party_2026'])
    .size()
    .reset_index(name='seats_2026')
)

region_2026.head()

region_2021 = region_2021.rename(
    columns={'winner_party_2021': 'party'}
)

region_2026 = region_2026.rename(
    columns={'winner_party_2026': 'party'}
)

region_2021.head()

region_2026.head()

"""
Merge the 2021 and 2026 regional seat distribution tables
to compare how party-wise seat counts changed across regions
between the two elections.
"""

regional_shift = pd.merge(
    region_2021,
    region_2026,
    on=['region', 'party'],
    how='outer'
)

regional_shift.head()

# Fill NA values with 0
regional_shift = regional_shift.fillna(0)

"""
Calculate the change in seats won by each party in each region
between the 2021 and 2026 elections.
Positive values indicate seat gains, while negative values indicate seat losses.
"""

regional_shift['seat_change'] = (
    regional_shift['seats_2026']
    - regional_shift['seats_2021']
)

regional_shift.head()

"""
Sort the regional seat distribution table by region and 2026 seat count
to make the comparison more organized and easier to interpret.
Within each region, parties with higher seat counts in 2026
will appear first.
"""

"""
This organized table helps identify which parties dominated,
gained, or lost seats across Tamil Nadu’s six regions
between the 2021 and 2026 elections.
"""

regional_shift = regional_shift.sort_values(
    by=['region', 'seats_2026'],
    ascending=[True, False]
)

regional_shift.head(20)

"""
Sort the regional seat comparison table by seat change
in descending order to identify the largest seat gains
between the 2021 and 2026 elections.
"""

regional_shift.sort_values(
    by='seat_change',
    ascending=False
).head(15)

"""
Sort the regional seat comparison table by seat change
in ascending order to identify the largest seat losses
between the 2021 and 2026 elections.
"""

regional_shift.sort_values(
    by='seat_change'
).head(15)

import plotly.express as px

fig = px.bar(
    regional_shift,
    x='region',
    y='seats_2026',
    color='party',
    barmode='group',
    hover_data=['seats_2021', 'seat_change'],
    title='Regional Seat Distribution - 2026'
)

fig.show()

# Export regional_shift as csv
regional_shift.to_csv(
    "regional_shift_analysis.csv",
    index=False
)

import plotly.express as px

fig = px.bar(
    regional_shift,
    x='region',
    y='seats_2026',
    color='party',
    barmode='group',
    hover_data=[
        'seats_2021',
        'seat_change'
    ],
    title='Regional Seat Distribution Comparison (2021 vs 2026)'
)

fig.show()

"""#Flip Story"""

# Filter constituencies where the winning party changed
# between the 2021 and 2026 elections

flipped_constituencies = election_comparison[
    election_comparison['winner_party_2021']
    != election_comparison['winner_party_2026']
]

flipped_constituencies.head()

# Count the total number of constituencies
# where the winning party changed

print(
    "Total Flipped Constituencies:",
    flipped_constituencies.shape[0]
)

# Count how many constituencies shifted
# from one party to another

flip_flow = (
    flipped_constituencies
    .groupby([
        'winner_party_2021',
        'winner_party_2026'
    ])
    .size()
    .reset_index(name='flip_count')
)

flip_flow

# Count flipped constituencies region-wise

region_flips = (
    flipped_constituencies
    .groupby('region_2021')
    .size()
    .reset_index(name='flip_count')
    .sort_values(
        by='flip_count',
        ascending=False
    )
)

region_flips

flip_flow

# Sort party-to-party constituency shifts
# by highest number of flipped constituencies

flip_flow = flip_flow.sort_values(
    by='flip_count',
    ascending=False
)

flip_flow.head(15)

import plotly.express as px

fig = px.bar(
    region_flips,
    x='region_2021',
    y='flip_count',
    color='flip_count',
    text='flip_count',
    title='Region-wise Flipped Constituencies'
)

fig.update_traces(textposition='outside')

fig.show()

# Export constituency flip flow table
# for Power BI Sankey visualization

flip_flow.to_csv(
    "flip_flow_analysis.csv",
    index=False
)

# Export region-wise flip analysis
# for dashboard and storytelling visuals

region_flips.to_csv(
    "region_flip_analysis.csv",
    index=False
)

"""#Vote Share Story"""

# Calculate total votes polled in each constituency for 2021

total_votes_2021 = (
    tn_2021_results
    .groupby('ac_number')['votes']
    .sum()
    .reset_index(name='total_votes_2021')
)

# Calculate total votes polled in each constituency for 2026

total_votes_2026 = (
    tn_2026_results
    .groupby('ac_number')['votes']
    .sum()
    .reset_index(name='total_votes_2026')
)

# Merge total constituency votes into both election datasets
# so that each candidate row also contains the total votes polled
# in that constituency for percentage and comparative analysis.

tn_2021_results = pd.merge(
    tn_2021_results,
    total_votes_2021,
    on='ac_number'
)

# Merge total constituency votes into both election datasets
# so that each candidate row also contains the total votes polled
# in that constituency for percentage and comparative analysis.

tn_2026_results = pd.merge(
    tn_2026_results,
    total_votes_2026,
    on='ac_number'
)

# Calculate candidate vote share percentage for 2021

tn_2021_results['vote_share_2021'] = (
    tn_2021_results['votes']
    / tn_2021_results['total_votes_2021']
) * 100

# Aggregate party vote share statewide - 2021
vote_share_2021 = (
    tn_2021_results
    .groupby('party')['votes']
    .sum()
    .reset_index(name='votes_2021')
)

# Aggregate party vote share statewide - 2026
vote_share_2026 = (
    tn_2026_results
    .groupby('party')['votes']
    .sum()
    .reset_index(name='votes_2026')
)

# Merge statewide totals
vote_share_comparison = pd.merge(
    vote_share_2021,
    vote_share_2026,
    on='party',
    how='outer'
).fillna(0)

# Calculate vote-share change
vote_share_comparison['vote_change'] = (
    vote_share_comparison['votes_2026']
    - vote_share_comparison['votes_2021']
)

# Sort parties by highest increase in votes
# between the 2021 and 2026 elections

vote_share_comparison.sort_values(
    by='vote_change',
    ascending=False
)


# This analysis identifies parties that gained
# the most votes between the 2021 and 2026 elections.

# Sort parties by largest decline in votes
# between the 2021 and 2026 elections

vote_share_comparison.sort_values(
    by='vote_change'
)

# This analysis identifies parties that experienced
# the largest reduction in votes between the two elections.

# Analyze TVK vote distribution across regions in 2026

tvk_region_votes = (
    tn_2026_results[
        tn_2026_results['party'] == 'TVK'
    ]
    .groupby('region')['votes']
    .sum()
    .reset_index(name='tvk_votes_2026')
    .sort_values(
        by='tvk_votes_2026',
        ascending=False
    )
)

tvk_region_votes

# Create an interactive bar chart to visualize
# TVK's regional vote distribution in the 2026 election,
# helping identify regions where the party performed strongest.

import plotly.express as px

fig = px.bar(
    tvk_region_votes,
    x='region',
    y='tvk_votes_2026',
    color='tvk_votes_2026',
    text='tvk_votes_2026',
    title='TVK Vote Distribution Across Regions (2026)'
)

fig.update_traces(textposition='outside')

fig.show()

vote_share_comparison.sort_values(
    by='vote_change',
    ascending=False
)

tvk_region_votes

tvk_region_votes = (
    tn_2026_results[
        tn_2026_results['party'] == 'TVK'
    ]
    .groupby('region')['votes']
    .sum()
    .reset_index(name='tvk_votes_2026')
)

tvk_region_votes

# Export to csv
tvk_region_votes.to_csv(
    "tvk_region_votes.csv",
    index=False
)

# Export to csv
vote_share_comparison.to_csv(
    "vote_share_comparison.csv",
    index=False
)

"""
---

# Final Conclusions

### Key Findings
- Regional dominance became more fragmented in 2026.
- Several constituencies changed political control.
- TVK emerged as a statewide electoral force.
- Electoral competition intensified across Tamil Nadu.

### Project Outcome
This project demonstrates analytical storytelling using election data, combining Python-based analysis with Power BI dashboard design and presentation-driven insight communication.

---
"""